Reciclame/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webpage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpage/urls.py
from django.urls import path
from . import views

app_name = 'webpage'
urlpatterns = [
    path('', views.index, name='index'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('agendar', views.agendar, name='agendar'),
    path('partners', views.partners, name='partners'),
    path('registro', views.registro, name='registro'),
    path('registro-centro', views.registroCentro, name='registro-centro'),
    path('login', views.login, name='login'),
    path('catalogo', views.catalogo, name='catalogo'),
    path('perfil', views.perfil, name='perfil'),
    path('logout', views.logout, name='logout'),
    path('citas', views.citas, name='citas'),
    path('centro', views.centro, name='centro'),
    path('cancelarcita/<int:id>', views.cancelarcita, name='cancelarcita'),
    path('historial_canje', views.historialCanje, name='historial_canje'),
]

webpage/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
import datetime
from django.utils import timezone

# Create your models here.
class UserProfile(AbstractUser):
    ROLES =(
        ('1','Usuario'),
        ('2', 'Centro'),
        ('3', 'Admin'),
    )
    rol = models.CharField(max_length=3, choices=ROLES)
    puntos_totales = models.IntegerField(default=0)




#Admin, Controlara los residuos disponibles para que no puedan levantar los centros cualquier residuo
class Residuo(models.Model):
    waste_name =models.CharField(max_length=100)
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.waste_name

#Admin, nomnbre de los centros de reciclaje disponibles
class Centro(models.Model):
    place_name = models.CharField(max_length=100)
    place_email = models.CharField(max_length=100)

    def __str__(self):
        return self.place_name

#El centro asigna los residuos que puede tener, siempre y cuando solo sea los dados de alta
class ResiduoLugar(models.Model):
    lugar = models.ForeignKey(Centro, on_delete=models.CASCADE)
    residuo = models.ForeignKey(Residuo, on_delete=models.CASCADE)
    limite = models.IntegerField()

    def __str__(self):
        return '%s - %s' % (self.lugar.place_name, self.residuo.waste_name)


class Punto(models.Model):
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    waste = models.ForeignKey(Residuo, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    total = models.IntegerField()


    def __str__(self):
        return '%s %s' % (self.user, self.waste)

class LimitWaste(models.Model):
    place = models.ForeignKey(Centro, on_delete=models.CASCADE)
    waste = models.ForeignKey(Residuo, on_delete=models.CASCADE)
    limit = models.IntegerField(default=0)

    def __str__(self):
        return '%s %s limite: %s' % (self.place,self.waste,self.limit)


class Premio(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='static/webpage/images/catalogo/')
    reward_points = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)
    stock = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Cita(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE,default=1)
    lugar = models.ForeignKey(Centro, on_delete=models.CASCADE)
    residuo = models.ForeignKey(Residuo, on_delete=models.CASCADE)
    fecha_cita = models.DateField(auto_now=False)
    num_residuos = models.IntegerField(default=1)
    fecha_aprobacion = models.DateField(default=None, blank=True, null=True)
    Estatus = models.IntegerField(default=0)

    def __str__(self):
        return str(self.fecha_cita)


class HistorialCanje(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    fecha = models.DateField()
    articulo = models.CharField(max_length=40)
    antes = models.IntegerField(default=0)
    despues = models.IntegerField(default=0)


class Partners(models.Model):
    nombre = models.CharField(max_length=50, default="Pendiente")
    descripcion = models.CharField(max_length=50, default=" ")
    direccion = models.CharField(max_length=100, default=" ")
    telefono = models.CharField(max_length=50, default=0)
    horario = models.CharField(max_length=25, default=" ")
    email = models.CharField(max_length=50, default=" ")
    pagina = models.CharField(max_length=80, default=" ")
    giro = models.CharField(max_length=40, default=" ")
    image = models.ImageField(upload_to='static/webpage/images/partners/', default="example.jpg")
    contacto = models.CharField(max_length=50, default="No disponible")

    def __str__(self):
        return self.nombre

webpage/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import get_template
from django.contrib import auth
from .models import *
from django.contrib.auth.decorators import login_required
import datetime



# Create your views here.
def index(request):
    return render(request, 'webpage/index.html')


def nosotros(request):
    if request.method == 'POST':
                nombre = request.POST['nombre']
                correo = request.POST['correo']
                descripcion = request.POST['descripcion']
                send_mail('Reciclamex',  # subject
                          'La persona ' + nombre + ' con el correo ' + correo + ' mando el siguiente mensaje por medio de la seccion de DUDAS: ' + descripcion,  # body
                          'slayerudg@gmail.com',  # domain email
                          ['slayerudg@gmail.com'],  # email that recieve
                          fail_silently=True  # show if fails
                          )
                return render(request, 'webpage/nosotros.html',
                              {'success': 'Tu Mensaje se ha enviado correctamente'})
    else:
        return render(request, 'webpage/nosotros.html')


@login_required(login_url="/login")
def agendar(request):
    user = UserProfile.objects.get(pk=request.session['id'])
    lugares = Centro.objects.all()
    residuos = Residuo.objects.all()
    limite = LimitWaste.objects.all()
    if user is not None:
        if user.rol == '1':
            if request.method == 'POST':
                cita = Cita()
                cita.lugar = Centro.objects.get(pk=request.POST['lugar'])
                cita.fecha_cita = request.POST['fecha']
                cita.residuo = Residuo.objects.get(pk=request.POST['residuo'])
                cita.num_residuos = request.POST['cantidad']
                cita.user = UserProfile.objects.get(pk=request.session['id'])
                cita.save()
                send_mail('Reciclamex',  # subject
                          'Se agendo una cita el dia'+ ' ' + str(cita.fecha_cita) + ' ' + 'en' + ' ' + str(cita.lugar) + ' ' + 'te esperamos',  # body
                          'slayerudg@gmail.com',  # domain email
                          ['slayerudg@gmail.com','manuelchairezudg@gmail.com','reciclamex.info@gmail.com', 'jmanuel.chairez@alumnos.udg.mx'],  # email that recieve
                          fail_silently=True  # show if fails
                          )
                return render(request, 'webpage/agendar.html',
                              {'success': 'Tu cita a sido Agendada exitosamente', 'lugares': lugares,
                               'residuos': residuos, 'limite': limite})
            else:
                return render(request, 'webpage/agendar.html',
                              {'lugares': lugares, 'residuos': residuos, 'limite': limite})
        elif user.rol == '2':
            return redirect('webpage:centro')
        elif user.rol == '3':
            return redirect('admin/')
    else:
        return render(request, 'webpage/index.html')


def partners(request):
    partner = Partners.objects.all()
    return render(request, 'webpage/partners.html', {"partner": partner})


def registro(request):
    if request.method == 'POST':
        if UserProfile.objects.filter(username=request.POST['username']).exists():
            return render(request, 'webpage/registro.html', {'error': 'Usuario ya registrado'})
        elif UserProfile.objects.filter(email=request.POST['email']).exists():
            return render(request, 'webpage/registro.html', {'error': 'Email ya registrado'})
        else:
            # usuario no esta en database y quiere una cuenta nueva
            if request.POST['pass'] == request.POST['pass2']:
                if request.POST['email'] == request.POST['email2']:
                    user = UserProfile.objects.create_user(request.POST['username'],
                                                           email=request.POST['email'],
                                                           password=request.POST['pass'],
                                                           rol='1')
                    user.first_name = request.POST['name']
                    user.last_name = request.POST['lastname']
                    user.save()
                    usuario = UserProfile.objects.get(username=request.POST['username'])
                    request.session['username'] = usuario.username
                    request.session['rol'] = usuario.rol
                    request.session['id'] = usuario.pk
                    auth.login(request, user)
                    return redirect('webpage:index')
                else:
                    return render(request, 'webpage/registro.html', {'error': 'Los emails no son iguales'})
            else:
                return render(request, 'webpage/registro.html', {'error': 'Las contraseñas no son Iguales'})
    else:
        return render(request, 'webpage/registro.html')


def registroCentro(request):
    try:
        user = UserProfile.objects.get(pk=request.session['id'])
    except:
        print('Entre ala exception')
        return redirect('webpage:index')
    if user is not None:
        if user.rol == '1':
            return redirect('webpage:index')
        elif user.rol == '2':
            return redirect('webpage:index')
        elif user.rol == '3':
            if request.method == 'POST':
                if UserProfile.objects.filter(username=request.POST['username']).exists():
                    return render(request, 'webpage/registro-centro.html', {'error': 'Usuario ya registrado'})
                elif UserProfile.objects.filter(email=request.POST['email']).exists():
                    return render(request, 'webpage/registro-centro.html', {'error': 'Email ya registrado'})
                else:
                    # usuario no esta en database y quiere una cuenta nueva
                    if request.POST['pass'] == request.POST['pass2']:
                        if request.POST['email'] == request.POST['email2']:
                            user = UserProfile.objects.create_user(request.POST['username'],
                                                                   email=request.POST['email'],
                                                                   password=request.POST['pass'],
                                                                   rol='2')
                            user.save()
                            return render(request, 'webpage/registro-centro.html',
                                          {'exito': 'Registro Exitoso'})
                        else:
                            return render(request, 'webpage/registro-centro.html',
                                          {'error': 'Los emails no son iguales'})
                    else:
                        return render(request, 'webpage/registro-centro.html',
                                      {'error': 'Las contraseñas no son Iguales'})
            else:
                return render(request, 'webpage/registro-centro.html')
    else:
        return redirect('webpage:index')


def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'], password=request.POST['pass'])
        if user is not None:
            usuario = UserProfile.objects.get(username=request.POST['username'])
            auth.login(request, user)
            print(usuario.rol)
            request.session['username'] = usuario.username
            request.session['rol'] = usuario.rol
            request.session['id'] = usuario.pk
            if usuario.rol == '1':
                return redirect('webpage:index')
            elif usuario.rol == '2':
                return redirect('webpage:centro')
            elif usuario.rol == '3':
                return redirect('webpage:index')
            else:
                return render(request, 'webpage/login.html',
                              {'error': 'la cuenta no tiene rol, habla con el administrador'})
        else:
            return render(request, 'webpage/login.html', {'error': 'username or password is incorrect'})
    else:
        return render(request, 'webpage/login.html')


def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('webpage:index')

@login_required(login_url="/login")
def catalogo(request):
    usuario = UserProfile.objects.get(id=request.session['id'])
    premio = Premio.objects.order_by('-pub_date')
    if request.method == 'POST':
        premio_canje = Premio.objects.get(pk=request.POST['premio_id'])
        hcanje = HistorialCanje()
        hcanje.user = UserProfile.objects.get(id=request.session['id'])
        hcanje.articulo = premio_canje.title
        hcanje.fecha = datetime.datetime.now()
        hcanje.antes = usuario.puntos_totales
        hcanje.despues = usuario.puntos_totales - premio_canje.reward_points
        hcanje.save()
        if usuario.puntos_totales < premio_canje.reward_points:
            msg = 'No tienes suficientes puntos para canjearlo'
            return render(request, 'webpage/catalogo.html', {'premios': premio, 'msg': msg})
        usuario.puntos_totales = usuario.puntos_totales - premio_canje.reward_points

        usuario.save()
        return redirect('webpage:perfil')
    return render(request, 'webpage/catalogo.html', {'premios': premio})


@login_required(login_url="/login")
def perfil(request):
    user = UserProfile.objects.get(pk=request.session['id'])
    articulos = Cita.objects.filter(user__cita=request.session['id'], user__cita__Estatus=1).all()
    if user is not None:
        if user.rol == '1':
            for numero in articulos:
                numeros = numero.num_residuos * numero.residuo.points
             #print(articulos)
            puntos = 0
            for articulo in articulos:

webpage/templates/base/base.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'webpage/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css"
          integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <!-- mapbox only -->
    <!-- <script src='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.js'></script>
    <link href='https://api.mapbox.com/mapbox-gl-js/v0.47.0/mapbox-gl.css' rel='stylesheet' /> -->
    <!-- leaflet + mapbox -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.3.3/dist/leaflet.css"
          integrity="sha512-Rksm5RenBEKSKFjgI3a41vrjkw4EVPlJ3+OiI65vTjIdo9brlAacEuKOiQ5OFh7cOI1bkDwLqdLw3Zg0cRJAAQ=="
          crossorigin=""/>
    <!-- Make sure you put this AFTER Leaflet's CSS -->
    <script src="https://unpkg.com/leaflet@1.3.3/dist/leaflet.js"
            integrity="sha512-tAGcCfR4Sc5ZP5ZoVz0quoZDYX5aCtEm/eu1KhSLj2c9eFrylXZknQYmxUssFaVJKvvc0dJQixhGjG2yXWiV9Q=="
            crossorigin=""></script>
    <title>Recicl@ame</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="d-flex flex-row d-lg-none align-items-center justify-content-center w-100">
            <a class="navbar-brand" href="{% url 'webpage:index' %}">
                <img class="img-fluid" src="{% static "webpage/images/Logo completo copy.png" %}">
            </a>
            <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
        <a class="navbar-brand d-none d-lg-flex" href="{% url 'webpage:index' %}">
            <img class="img-fluid" src="{% static "webpage/images/Logo completo copy.png" %}">
        </a>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav w-100 align-items-center">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'webpage:index' %}">Inicio <span
                            class="sr-only">(current)</span></a>
                </li>
                {% if user.rol == '1' %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'webpage:agendar' %}">Agenda tu cita</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webpage:nosotros' %}">Nosotros</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webpage:partners' %}">Partners</a>
                </li>
                {% if user.rol == '1' %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'webpage:catalogo' %}">Catalogo</a>
                </li>
                {% endif %}
                {% if user.rol == '2' %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'webpage:centro' %}">Revisar Citas</a>
                    </li>
                {% endif %}
                {% if user.rol == '3' %}
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'admin:index' %}"><button class="btn btn-info">Admin Panel</button></a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'webpage:registro-centro' %}"><button class="btn btn-primary">Agregar Usuario Centro</button></a>
                    </li>
                {% endif %}
                {% if  user.is_authenticated %}
                    {% if user.rol == '1' %}
                        <li class="nav-item ml-lg-auto">
                            <a class="btn btn-success" href="{% url 'webpage:perfil' %}">Mi Perfil</a>
                        </li>
                        <li class="nav-item ml-3">
                            <a class="btn btn-danger" href="javascript:{document.getElementById('logout').submit()}"
                               onclick="">Logout</a>
                        </li>
                        <form id="logout" method="POST" action="{% url 'webpage:logout' %}">
                            {% csrf_token %}
                            <input type="hidden"/>
                        </form>
                    {% else %}
                        <li class="nav-item ml-3 ml-lg-auto">
                            <a class="btn btn-danger" href="javascript:{document.getElementById('logout').submit()}"
                               onclick="">Logout</a>
                        </li>
                        <form id="logout" method="POST" action="{% url 'webpage:logout' %}">
                            {% csrf_token %}
                            <input type="hidden"/>
                        </form>
                    {% endif %}
                {% else %}
                    <div class="container d-flex flex-row justify-content-around">
                        <li class="nav-item ml-lg-auto">
                            <a class="btn btn-outline-success" href="{% url 'webpage:registro' %}">Registro</a>
                        </li>
                        <li class="nav-item">
                            <a class="btn btn-outline-primary ml-3" href="{% url 'webpage:login' %}">Inicio de
                                sesión</a>
                        </li>
                    </div>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>
<main>
    {% block contenedor %}

    {% endblock %}
</main>
<footer style="background-color: #505050">
    <div class="container text-center">
        <p>Reciclamex</p>
        <p>Reciclamex.info@gmail.com</p>
        <p>
            <a href="https://www.facebook.com/Reciclame-270737653628360/" target="_blank"><i class="m-2 fab fa-facebook fa-3x"></i></a>
            <a href="https://www.instagram.com/reciclame/" target="_blank"><i class="m-2 fab fa-instagram fa-3x"></i></a>
            <a href="https://www.youtube.com/channel/UCqHDoG3DJtijXNe4U-QXH-Q/featured?disable_polymer=1" target="_blank"><i
                    class="m-2 fab fa-youtube fa-3x"></i></a>
        </p>
    </div>
</footer>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>
</html>

webpage/templates/base/base_centro.html
<!DOCTYPE html>
{% load static %}
<html lang="es">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'webpage/dashboard.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.2/css/all.css"
          integrity="sha384-/rXc/GQVaYpyDdyxK+ecHPVYJSN9bmVFBvjA/9eOB+pb3F2w2N6fc5qB9Ew5yIns" crossorigin="anonymous">
    <title>Recicl@ame</title>
</head>
<body>
<nav class="navbar navbar-dark fixed-top bg-dark flex-md-nowrap p-0 shadow">
    <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'webpage:index' %}">Reciclamex</a>
    <h4 class="mr-auto ml-2" style="color: White">Bienvenido <b> {{ user }} </b></h4>
    <ul class="navbar-nav px-3">
        <li class="nav-item ml-3">
            <a class="btn btn-danger" href="javascript:{document.getElementById('logout').submit()}"
               onclick="">Logout</a>
        </li>
        <form id="logout" method="POST" action="{% url 'webpage:logout' %}">
            {% csrf_token %}
            <input type="hidden"/>
        </form>

    </ul>
</nav>

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-2 d-none d-md-block bg-light sidebar">
            <div class="sidebar-sticky">
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">
                            <span data-feather="home"></span>
                            Dashboard <span class="sr-only">(current)</span>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="file"></span>
                            Citas
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="shopping-cart"></span>
                            Productos
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <span data-feather="users"></span>
                            Customers
                        </a>
                    </li>
                </ul>
            </div>
        </nav>
        <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
            {% block contenedor %}

            {% endblock %}
        </main>
    </div>
</div>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
        integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
        integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>
    feather.replace()
</script>

<!-- Graphs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script>
    var ctx = document.getElementById("myChart");
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
            datasets: [{
                data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
                lineTension: 0,
                backgroundColor: 'transparent',
                borderColor: '#007bff',
                borderWidth: 4,
                pointBackgroundColor: '#007bff'
            }]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: false
                    }
                }]
            },
            legend: {
                display: false,
            }
        }
    });
</script>
</body>
</html>