Reciclame/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('webpage.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webpage/urls.py
from django.urls import path
from . import views

app_name = 'webpage'
urlpatterns = [
    path('', views.index, name='index'),
    path('nosotros', views.nosotros, name='nosotros'),
    path('agendar', views.agendar, name='agendar'),
    path('partners', views.partners, name='partners'),
    path('registro', views.registro, name='registro'),
    path('registro-centro', views.registroCentro, name='registro-centro'),
    path('login', views.login, name='login'),
    path('catalogo', views.catalogo, name='catalogo'),
    path('perfil', views.perfil, name='perfil'),
    path('logout', views.logout, name='logout'),
    path('citas', views.citas, name='citas'),
    path('centro', views.centro, name='centro'),
    path('cancelarcita/<int:id>', views.cancelarcita, name='cancelarcita'),
    path('historial_canje', views.historialCanje, name='historial_canje'),
]

webpage/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
import datetime
from django.utils import timezone

# Create your models here.
class UserProfile(AbstractUser):
    ROLES =(
        ('1','Usuario'),
        ('2', 'Centro'),
        ('3', 'Admin'),
    )
    rol = models.CharField(max_length=3, choices=ROLES)
    puntos_totales = models.IntegerField(default=0)




#Admin, Controlara los residuos disponibles para que no puedan levantar los centros cualquier residuo
class Residuo(models.Model):
    waste_name =models.CharField(max_length=100)
    points = models.IntegerField(default=0)

    def __str__(self):
        return self.waste_name

#Admin, nomnbre de los centros de reciclaje disponibles
class Centro(models.Model):
    place_name = models.CharField(max_length=100)
    place_email = models.CharField(max_length=100)

    def __str__(self):
        return self.place_name

#El centro asigna los residuos que puede tener, siempre y cuando solo sea los dados de alta
class ResiduoLugar(models.Model):
    lugar = models.ForeignKey(Centro, on_delete=models.CASCADE)
    residuo = models.ForeignKey(Residuo, on_delete=models.CASCADE)
    limite = models.IntegerField()

    def __str__(self):
        return '%s - %s' % (self.lugar.place_name, self.residuo.waste_name)


class Punto(models.Model):
    user = models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    waste = models.ForeignKey(Residuo, on_delete=models.CASCADE)
    cantidad = models.IntegerField()
    total = models.IntegerField()


    def __str__(self):
        return '%s %s' % (self.user, self.waste)

class LimitWaste(models.Model):
    place = models.ForeignKey(Centro, on_delete=models.CASCADE)
    waste = models.ForeignKey(Residuo, on_delete=models.CASCADE)
    limit = models.IntegerField(default=0)

    def __str__(self):
        return '%s %s limite: %s' % (self.place,self.waste,self.limit)


class Premio(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=255)
    image = models.ImageField(upload_to='static/webpage/images/catalogo/')
    reward_points = models.IntegerField(default=0)
    pub_date = models.DateTimeField(auto_now_add=True)
    stock = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class Cita(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE,default=1)
    lugar = models.ForeignKey(Centro, on_delete=models.CASCADE)
    residuo = models.ForeignKey(Residuo, on_delete=models.CASCADE)
    fecha_cita = models.DateField(auto_now=False)
    num_residuos = models.IntegerField(default=1)
    fecha_aprobacion = models.DateField(default=None, blank=True, null=True)
    Estatus = models.IntegerField(default=0)

    def __str__(self):
        return str(self.fecha_cita)


class HistorialCanje(models.Model):
    user = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    fecha = models.DateField()
    articulo = models.CharField(max_length=40)
    antes = models.IntegerField(default=0)
    despues = models.IntegerField(default=0)


class Partners(models.Model):
    nombre = models.CharField(max_length=50, default="Pendiente")
    descripcion = models.CharField(max_length=50, default=" ")
    direccion = models.CharField(max_length=100, default=" ")
    telefono = models.CharField(max_length=50, default=0)
    horario = models.CharField(max_length=25, default=" ")
    email = models.CharField(max_length=50, default=" ")
    pagina = models.CharField(max_length=80, default=" ")
    giro = models.CharField(max_length=40, default=" ")
    image = models.ImageField(upload_to='static/webpage/images/partners/', default="example.jpg")
    contacto = models.CharField(max_length=50, default="No disponible")

    def __str__(self):
        return self.nombre

webpage/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from django.conf import settings
from django.template.loader import get_template
from django.contrib import auth
from .models import *
from django.contrib.auth.decorators import login_required
import datetime



# Create your views here.
def index(request):
    return render(request, 'webpage/index.html')


def nosotros(request):
    if request.method == 'POST':
                nombre = request.POST['nombre']
                correo = request.POST['correo']
                descripcion = request.POST['descripcion']
                send_mail('Reciclamex',  # subject
                          'La persona ' + nombre + ' con el correo ' + correo + ' mando el siguiente mensaje por medio de la seccion de DUDAS: ' + descripcion,  # body
                          'slayerudg@gmail.com',  # domain email
                          ['slayerudg@gmail.com'],  # email that recieve
                          fail_silently=True  # show if fails
                          )
                return render(request, 'webpage/nosotros.html',
                              {'success': 'Tu Mensaje se ha enviado correctamente'})
    else:
        return render(request, 'webpage/nosotros.html')


@login_required(login_url="/login")
def agendar(request):
    user = UserProfile.objects.get(pk=request.session['id'])
    lugares = Centro.objects.all()
    residuos = Residuo.objects.all()
    limite = LimitWaste.objects.all()
    if user is not None:
        if user.rol == '1':
            if request.method == 'POST':
                cita = Cita()
                cita.lugar = Centro.objects.get(pk=request.POST['lugar'])
                cita.fecha_cita = request.POST['fecha']
                cita.residuo = Residuo.objects.get(pk=request.POST['residuo'])
                cita.num_residuos = request.POST['cantidad']
                cita.user = UserProfile.objects.get(pk=request.session['id'])
                cita.save()
                send_mail('Reciclamex',  # subject
                          'Se agendo una cita el dia'+ ' ' + str(cita.fecha_cita) + ' ' + 'en' + ' ' + str(cita.lugar) + ' ' + 'te esperamos',  # body
                          'slayerudg@gmail.com',  # domain email
                          ['slayerudg@gmail.com','manuelchairezudg@gmail.com','reciclamex.info@gmail.com', 'jmanuel.chairez@alumnos.udg.mx'],  # email that recieve
                          fail_silently=True  # show if fails
                          )
                return render(request, 'webpage/agendar.html',
                              {'success': 'Tu cita a sido Agendada exitosamente', 'lugares': lugares,
                               'residuos': residuos, 'limite': limite})
            else:
                return render(request, 'webpage/agendar.html',
                              {'lugares': lugares, 'residuos': residuos, 'limite': limite})
        elif user.rol == '2':
            return redirect('webpage:centro')
        elif user.rol == '3':
            return redirect('admin/')
    else:
        return render(request, 'webpage/index.html')


def partners(request):
    partner = Partners.objects.all()
    return render(request, 'webpage/partners.html', {"partner": partner})


def registro(request):
    if request.method == 'POST':
        if UserProfile.objects.filter(username=request.POST['username']).exists():
            return render(request, 'webpage/registro.html', {'error': 'Usuario ya registrado'})
        elif UserProfile.objects.filter(email=request.POST['email']).exists():
            return render(request, 'webpage/registro.html', {'error': 'Email ya registrado'})
        else:
            # usuario no esta en database y quiere una cuenta nueva
            if request.POST['pass'] == request.POST['pass2']:
                if request.POST['email'] == request.POST['email2']:
                    user = UserProfile.objects.create_user(request.POST['username'],
                                                           email=request.POST['email'],
                                                           password=request.POST['pass'],
                                                           rol='1')
                    user.first_name = request.POST['name']
                    user.last_name = request.POST['lastname']
                    user.save()
                    usuario = UserProfile.objects.get(username=request.POST['username'])
                    request.session['username'] = usuario.username
                    request.session['rol'] = usuario.rol
                    request.session['id'] = usuario.pk
                    auth.login(request, user)
                    return redirect('webpage:index')
                else:
                    return render(request, 'webpage/registro.html', {'error': 'Los emails no son iguales'})
            else:
                return render(request, 'webpage/registro.html', {'error': 'Las contraseñas no son Iguales'})
    else:
        return render(request, 'webpage/registro.html')


def registroCentro(request):
    try:
        user = UserProfile.objects.get(pk=request.session['id'])
    except:
        print('Entre ala exception')
        return redirect('webpage:index')
    if user is not None:
        if user.rol == '1':
            return redirect('webpage:index')
        elif user.rol == '2':
            return redirect('webpage:index')
        elif user.rol == '3':
            if request.method == 'POST':
                if UserProfile.objects.filter(username=request.POST['username']).exists():
                    return render(request, 'webpage/registro-centro.html', {'error': 'Usuario ya registrado'})
                elif UserProfile.objects.filter(email=request.POST['email']).exists():
                    return render(request, 'webpage/registro-centro.html', {'error': 'Email ya registrado'})
                else:
                    # usuario no esta en database y quiere una cuenta nueva
                    if request.POST['pass'] == request.POST['pass2']:
                        if request.POST['email'] == request.POST['email2']:
                            user = UserProfile.objects.create_user(request.POST['username'],
                                                                   email=request.POST['email'],
                                                                   password=request.POST['pass'],
                                                                   rol='2')
                            user.save()
                            return render(request, 'webpage/registro-centro.html',
                                          {'exito': 'Registro Exitoso'})
                        else:
                            return render(request, 'webpage/registro-centro.html',
                                          {'error': 'Los emails no son iguales'})
                    else:
                        return render(request, 'webpage/registro-centro.html',
                                      {'error': 'Las contraseñas no son Iguales'})
            else:
                return render(request, 'webpage/registro-centro.html')
    else:
        return redirect('webpage:index')


def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'], password=request.POST['pass'])
        if user is not None:
            usuario = UserProfile.objects.get(username=request.POST['username'])
            auth.login(request, user)
            print(usuario.rol)
            request.session['username'] = usuario.username
            request.session['rol'] = usuario.rol
            request.session['id'] = usuario.pk
            if usuario.rol == '1':
                return redirect('webpage:index')
            elif usuario.rol == '2':
                return redirect('webpage:centro')
            elif usuario.rol == '3':
                return redirect('webpage:index')
            else:
                return render(request, 'webpage/login.html',
                              {'error': 'la cuenta no tiene rol, habla con el administrador'})
        else:
            return render(request, 'webpage/login.html', {'error': 'username or password is incorrect'})
    else:
        return render(request, 'webpage/login.html')


def logout(request):
    if request.method == 'POST':
        auth.logout(request)
        return redirect('webpage:index')

@login_required(login_url="/login")
def catalogo(request):
    usuario = UserProfile.objects.get(id=request.session['id'])
    premio = Premio.objects.order_by('-pub_date')
    if request.method == 'POST':
        premio_canje = Premio.objects.get(pk=request.POST['premio_id'])
        hcanje = HistorialCanje()
        hcanje.user = UserProfile.objects.get(id=request.session['id'])
        hcanje.articulo = premio_canje.title
        hcanje.fecha = datetime.datetime.now()
        hcanje.antes = usuario.puntos_totales
        hcanje.despues = usuario.puntos_totales - premio_canje.reward_points
        hcanje.save()
        if usuario.puntos_totales < premio_canje.reward_points:
            msg = 'No tienes suficientes puntos para canjearlo'
            return render(request, 'webpage/catalogo.html', {'premios': premio, 'msg': msg})
        usuario.puntos_totales = usuario.puntos_totales - premio_canje.reward_points

        usuario.save()
        return redirect('webpage:perfil')
    return render(request, 'webpage/catalogo.html', {'premios': premio})


@login_required(login_url="/login")
def perfil(request):
    user = UserProfile.objects.get(pk=request.session['id'])
    articulos = Cita.objects.filter(user__cita=request.session['id'], user__cita__Estatus=1).all()
    if user is not None:
        if user.rol == '1':
            for numero in articulos:
                numeros = numero.num_residuos * numero.residuo.points
             #print(articulos)
            puntos = 0
            for articulo in articulos:

webpage/templates/webpage/aprobar_cita.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Aprobar Cita</title>
</head>
<body>

</body>
</html>

webpage/templates/webpage/catalogo.html
{% extends "base/base.html" %}
{% load static %}
{% block contenedor %}
    <article>
        <section class="section-name p-2 pl-4 d-flex flex-row align-items-center">
            <h4>Catalogo</h4>
            <div class="d-none d-lg-block ml-auto">
                <div class="btn btn-danger ml-2">
                    <i class="fas fa-tv ml-auto"> TV = 100</i>
                </div>
                <div class="btn btn-dark ml-2">
                    <i class="fas fa-laptop"> PC = 80 </i>
                </div>
                <div class="btn btn-info ml-2">
                    <i class="fas fa-battery-empty"> Pilas = 5</i>
                </div>
                <div class="btn btn-light ml-2">
                    <i class="fas fa-blender"> Electrodomesticos = 40 </i>
                </div>
                <div class="btn btn-warning ml-2">
                    <i class="fas fa-mobile-alt"> Celulares = 50</i>
                </div>
                <div class="btn btn-success ml-2">
                    <i class="fas fa-print"> Impresoras = 40</i>
                </div>
            </div>
        </section>
        {% if premios %}
            <section class="d-flex flex-column flex-md-row partners-background">

                <div class="row p-4 flex-wrap w-100">
                    {% for premio in premios %}
                        <div class="col-md-3">
                            <div class="card mb-4 box-shadow">
                                <img class="card-img-top"
                                     src="{% static "webpage/images/catalogo/"%}{{ premio.image }}"
                                     alt="Card image cap" height="230px">
                                <div class="card-body">
                                    <h3>{{ premio.title }}</h3>
                                    {% if premio.stock <= 0 %}
                                        <span style="color: red;">Agotado</span>
                                    {% elif premio.stock <= 30 and premio.stock > 0 %}
                                        <span style="color: goldenrod;">Pocas Existencias</span>
                                    {% elif premio.stock > 30 %}
                                        <span style="color: Green;">Existencias</span>
                                    {% endif %}
                                    <p class="card-text">{{ premio.description }}</p>
                                    <p class="text-center"><i>{{ premio.reward_points }} Puntos</i></p>
                                    {% if user.rol == '1' %}
                                        <form class="d-flex justify-content-center align-items-center"
                                              action="{% url 'webpage:catalogo' %}" method="post">
                                            {% csrf_token %}
                                            <input type="hidden" name="premio_id" value="{{ premio.id }}">
                                            <button type="submit" class="premio-placeholder btn btn-success w-75">
                                                Canjear Producto </button>
                                        </form>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </section>
        {% else %}
            <section class="d-flex justify-content-center align-content-center mt-5">
                <h2>No hay premios Disponibles</h2>
            </section>
        {% endif %}

    </article>
{% endblock %}

webpage/templates/webpage/centro.html
{% extends "base/base_centro.html" %}
{% load static %}
{% block contenedor %}

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
        <h1 class="h2"></h1>
    </div>

    <h2>Citas de {{ user }}</h2>
    <div class="container">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Lugar</th>
                        <th scope="col">Usuario</th>
                        <th scope="col">Residuo</th>
                        <th scope="col">Numero</th>
                        <th scope="col">fecha</th>
                        <th scope="col">aprobación</th>
                        <th scope="col">ID</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for citas in cita %}
                        <tr>
                            <th scope="row">{{ citas.lugar }}</th>
                            <td>{{ citas.user.first_name }}</td>
                            <td>{{ citas.residuo }}</td>
                            <td>{{ citas.num_residuos }}</td>
                            <td>{{ citas.fecha_cita }}</td>
                            {% if citas.fecha_aprobacion is not none %}
                                <td>{{ citas.fecha_aprobacion }}</td>
                            {% else %}
                                <td>
                                        <button>Aprobar</button>
                                </td>
                            {% endif %}
                            <td>{{ citas.id }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>

{% endblock %}

webpage/templates/webpage/login.html
{% extends "base/base.html" %}
{% load static %}
{% block contenedor %}
    <article>
        <section class="section-name p-2 pl-4">
            <h4>login</h4>
        </section>
        <section class="d-flex flex-column p-1">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <div class="d-flex flex-column row align-items-center">
                <div class="col-md-6 text-center d-flex flex-row align-items-center justify-content-center">
                    <img src="{% static "webpage/images/Logo cuadrado.png" %}">
                    <h2>Inicio de Sesión</h2>
                </div>
                <div class="d-flex col-md-6">
                   <form method="post" action="{% url 'webpage:login' %}" class="w-100 p-4">
                       {% csrf_token %}
                      <div class="form-group">
                        <label for="username">Usuario</label>
                        <input id="username" type="text" name="username" class="form-control">
                      </div>
                      <div class="form-group">
                        <label for="pass">Contraseña</label>
                        <input id="pass" name="pass" type="password" class="form-control">
                      </div>
                      <div class="form-group text-center">
                        <button type="submit" class="btn btn-success">Ingresar</button>
                      </div>
                    </form>
                </div>
            </div>
        </section>
    </article>
{% endblock %}

webpage/templates/webpage/perfil.html
{% extends "base/base.html" %}
{% load static %}
{% block contenedor %}
    <article>
        <section class="section-name p-2 pl-4">
            <h4>Mi perfil</h4>
        </section>
        <section class="d-flex flex-column partners-background">
            <div class="d-flex flex-row container mt-1 mb-1 align-items-center w-100">
                <i class="far fa-user fa-3x"></i>
                <h2 class="ml-2 mt-1">{{ user.first_name }} {{ user.last_name }} "{{ user }}"</h2>
                <a class="ml-auto" href="{% url 'webpage:citas' %}">
                    <button class="btn" style="background-color: #8DCDE1;color: #505050">Mis Citas</button>
                </a>
                <a class="ml-auto" href="{% url 'webpage:historial_canje' %}">
                    <button class="btn" style="background-color: #8DCDE1;color: #505050">Mis Canjes</button>
                </a>
            </div>
            <div class="d-flex flex-column w-100 p-5 container justify-content-center align-items-center"
                 style="background-color: #ECF2F3">
                <h4 class="font-weight-bold">Total de Puntos</h4>
                <h3 class="display-3">{{ user.puntos_totales }}</h3>
            </div>
            <div class="container d-flex flex-column mt-3">
                <h3>Residuos Reciclados</h3>
                <p>Estos son los residuos electronicos que has entregado</p>
                {% for articulo in articulos %}
                    <div class="d-flex align-items-center justify-content-around p-3 flex-wrap">
                    <div class="d-flex flex-column justify-content-center align-items-center">
                        <b class="num-icon rounded-circle">{{  articulo.cantidad }}</b>
                        <p class="mt-1">{{ articulo.waste.waste_name }}</p>
                    </div>
                {% endfor %}

                </div>
            </div>
        </section>
    </article>
{% endblock %}

webpage/templates/webpage/registro-centro.html
{% extends "base/base.html" %}
{% load static %}
{% block contenedor %}

    <article>
        <section class="section-name p-2 pl-4">
            <h4>Registro de Centro</h4>
        </section>
        <section class="d-flex flex-column p-1">
            <h2>Crear Cuenta de Administrador de Centro</h2>
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            {% if exito %}
                <div class="alert alert-success" role="alert">
                    {{ exito }}
                </div>
            {% endif %}
            <div class="d-flex flex-column flex-md-row row justify-content-center align-items-center">
                <div class="col-md-6 text-center">
                    <img class="w-50" src="{% static "webpage/images/Logo cuadrado.png" %}">
                </div>
                <div class="d-flex col-md-6">
                    <form method="post" action="{% url 'webpage:registro-centro' %}" class="w-100 p-4">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Nombre de Usuario</label>
                            <input id="username" name="username" type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input name="email" id="email" type="email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email2">Confirmar Email</label>
                            <input id="email2" name="email2" type="email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="pass">Contraseña</label>
                            <input id="pass" name="pass" type="password" class="form-control"
                                   placeholder="Minimo 8 digitos"
                                   min="8">
                        </div>
                        <div class="form-group">
                            <label for="pass2">Confirmar Contraseña</label>
                            <input id="pass2" name="pass2" type="password" class="form-control"
                                   placeholder="Minimo 8 digitos"
                                   min="8">
                        </div>
                        <button type="submit" class="btn btn-success">Registrarse</button>
                    </form>
                </div>
            </div>
        </section>
    </article>
{% endblock %}

webpage/templates/webpage/registro.html
{% extends "base/base.html" %}
{% load static %}
{% block contenedor %}

    <article>
        <section class="section-name p-2 pl-4">
            <h4>Registro</h4>
        </section>
        <section class="d-flex flex-column p-1">
            <h2>Crear Cuenta</h2>
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <div class="d-flex flex-column flex-md-row row justify-content-center align-items-center">
                <div class="col-md-6 text-center">
                    <img class="w-50" src="{% static "webpage/images/Logo cuadrado.png" %}">
                </div>
                <div class="d-flex col-md-6">
                    <form method="post" action="{% url 'webpage:registro' %}" class="w-100 p-4">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="username">Nombre de Usuario</label>
                            <input id="username" name="username" type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="name">Nombre</label>
                            <input id="name" name="name" type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="lastname">Apellidos</label>
                            <input id="lastname" name="lastname" type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email">Email</label>
                            <input name="email" id="email" type="email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="email2">Confirmar Email</label>
                            <input id="email2" name="email2" type="email" class="form-control">
                        </div>
                        <div class="form-group">
                            <label for="pass">Contraseña</label>
                            <input id="pass" name="pass" type="password" class="form-control"
                                   placeholder="Minimo 8 digitos"
                                   min="8">
                        </div>
                        <div class="form-group">
                            <label for="pass2">Confirmar Contraseña</label>
                            <input id="pass2" name="pass2" type="password" class="form-control"
                                   placeholder="Minimo 8 digitos"
                                   min="8">
                        </div>
                        <div class="form-group">
                            <label for="fecha_n">Fecha de Nacimiento</label>
                            <input id="fecha_n" name="fecha_n" type="date" class="form-control" min="8">
                        </div>
                        <div class="form-group">
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="sexo" id="mujer" value="mujer">
                                <label class="form-check-label" for="mujer">Mujer</label>
                            </div>
                            <div class="form-check form-check-inline">
                                <input class="form-check-input" type="radio" name="sexo" id="hombre" value="hombre">
                                <label class="form-check-label" for="hombre">Hombre</label>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-success">Registrarse</button>
                    </form>
                </div>
            </div>
        </section>
    </article>
{% endblock %}